// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'learnify_lms';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CAIRO_BLACK = 'Cairo-Black';
  static const String CAIRO_BOLD = 'Cairo-Bold';
  static const String CAIRO_EXTRABOLD = 'Cairo-ExtraBold';
  static const String CAIRO_EXTRALIGHT = 'Cairo-ExtraLight';
  static const String CAIRO_LIGHT = 'Cairo-Light';
  static const String CAIRO_MEDIUM = 'Cairo-Medium';
  static const String CAIRO_REGULAR = 'Cairo-Regular';
  static const String CAIRO_SEMIBOLD = 'Cairo-SemiBold';
}
